dashboard_employes_index:
    path: /list
    controller: App\Controller\Back\EmployesController::listAction
    
dashboard_employes_details:
    path: /{id}/details
    controller: App\Controller\Back\EmployesController::showAction
    
dashboard_employes_new:
    path: /new
    controller: App\Controller\Back\EmployesController::newEmploye   
    
dashboard_employes_new_traitement:
    path: /new_traitement
    controller: App\Controller\Back\EmployesController::newEmployeAction       
    
dashboard_employes_edit:
    path: /{id}/edit
    controller: App\Controller\Back\EmployesController::editEmploye    
    
dashboard_employes_edit_traitement:
    path: /{id}/edit_traitement
    controller: App\Controller\Back\EmployesController::editEmployeAction
    
dashboard_employes_status:
    path: /{id}/edit_status
    controller: App\Controller\Back\EmployesController::employeStatus       
    
dashboard_employes_delete:
    path: /{id}/delete
    controller: App\Controller\Back\EmployesController::deleteAction    
